### ISSUE TITLE
py3k failure: refers to xrange

### ISSUE THREAD

**Issue by ruidc** [divio/djangocms-column#13]
http://dpaste.com/hold/1731570/

python3.3/site-packages/djangocms_column/cms_plugins.py" in save_model
  26.         for x in xrange(int(form.cleaned_data['create'])):

**Comment by trawick** [comment]
Fixed in https://github.com/divio/djangocms-column/commit/d2c1c315d6883300eff80c3972b5c61d74734c5e#diff-fb141d0ec65e2c5e54da16e345e4eaad and in releases 1.4 and 1.5

**Comment by mkoistinen** [comment]
Fixed as per the above.
