### ISSUE TITLE
save_model() on develop branch?

### ISSUE THREAD

**Issue by marksweb** [divio/djangocms-column#23]
I just started looking at the source to try to figure out an issue I've logged on CMS (https://github.com/divio/django-cms/issues/4117) & was going to do some PEP8/formatting changes as things were a nightmare to read, but noticed code on master (https://github.com/divio/djangocms-column/blob/master/djangocms_column/cms_plugins.py#L24) doesn't exist on develop.

What's the state of affairs with the branches? Have changes been applied to master instead of dev?

**Comment by yakky** [comment]
Develop was *a lot* behind master. Pugins usually does not adopt the develop/master branching model. But I agree that master and develop should be *at least* syncronised
