### ISSUE TITLE
support django 1.10?

### ISSUE THREAD

**Issue by benzkji** [divio/djangocms-column#32]
or is it abandoned?

**Comment by jedie** [comment]
seems to be a dead project?!?

What's about django v1.11 TLS support?

**Comment by benzkji** [comment]
communication is everything...I mean, a short "yea, we dont support this anymore, please use this or that alternative" or whatever, is at least a clear message.

**Comment by vstoykov** [comment]
There is support for 1.11 (2f0a78cde7f5f34c1c925b649f8e2aa6b2ad8145) in master but is not released yet #34

**Comment by benzkji** [comment]
Thank you!

**Comment by czpython** [comment]
Released
