### ISSUE TITLE
Pypi Version 

### ISSUE THREAD

**Issue by aventurella** [divio/djangocms-column#34]
The current version on pypi supports `Django<1.10`

But the latest on github supports `Django<2`
https://github.com/divio/djangocms-column/blob/master/setup.py#L9

It seems the pypi version needs to be updated

**Comment by T4m** [comment]
Any update on that ?

**Comment by trent** [comment]
I am running into an issue now related to this as pip installing this package after installing django-cms in a new project (as instructed in following django-cms "How to install django CMS by hand") downgrades the Django version installed with django-cms and raises an exception:
```
AttributeError: 'WSGIRequest' object has no attribute 'user'
```

**Comment by tidenhub** [comment]
I would really appreciate if you create and upload a new version.

**Comment by jedie** [comment]
+1 see also #32

**Comment by mpeuss** [comment]
+1

**Comment by vstoykov** [comment]
+1

**Comment by wismill** [comment]
+1

**Comment by dmcken** [comment]
At the moment I am getting the following when attempting to install using the "djangocms" command

```
Creating the project
Please wait while I install dependencies
If I am stuck for a long time, please check for connectivity / PyPi issues
djangocms-column 1.7.0 has requirement django<1.10,>=1.8, but you'll have django 1.11.13 which is incompatible.
Dependencies installed
```

As far as I can tell the package is no longer installing. I'm guessing I may need to take this up with djangocms themselves as there is a broken dependency.

**Comment by benzkji** [comment]
looks like this takes some time ;-)

**Comment by benzkji** [comment]
I've used it once, and it taught me a lot about using half maintained 3rd party code...I mean, nothing against divio, this ist just how open source works, and the way it goes, sometimes.

**Comment by renderbox** [comment]
Can you please push out a 1.7.1 with the fix to pypi?  Thanks!

**Comment by chris-tan-ity** [comment]
While we're waiting for the update to pypi here is a workaround I found -  we can use pipenv to install git repos, similar to how it's done with pip:

``pipenv install git+https://github.com/divio/djangocms-column.git#egg=djangocms-column``

The only issue is that its dependencies will not be resolved but I believe this is not an issue as it has no dependencies.

**Comment by czpython** [comment]
1.8.0 released to PyPi

**Comment by evildmp** [comment]
Thanks @czpython!
