### ISSUE TITLE
Add and release support for Django 2.2

### ISSUE THREAD

**Issue by jandd** [divio/djangocms-column#38]
Please merge e964416 from https://github.com/isotoma/djangocms-column and release to PyPI to add support for Django 2.2 which is the current Django LTS release.

**Comment by MichaelAnckaert** [comment]
Is there something blocking PR (#39)? We have a number of websites in production that we want to update to Django 2.2.

**Comment by lggwettmann** [comment]
Same here... We'd like to even update to 3.0 as fast as possible and Django CMS is holding us back but 2.2 would be appropriate. We'd be very thankful for a fast solution for this.

**Comment by Aiky30** [comment]
Resolved in 1.10.0: https://pypi.org/project/djangocms-column/1.10.0/
