### ISSUE TITLE
Support for Django 3?

### ISSUE THREAD

**Issue by MattDMo** [divio/djangocms-column#44]
Currently, `setup.py` has the following requirement:
```py
'Django>=1.11,<3.0'`
```

Does djangocms-column specifically NOT support Django 3+, or can the requirement be changed? I'm using CMS on Django 3.0.7 and would like to be able to use column as well. I see PR #43 only has one minor change to `models.py` requiring `six`, which I believe CMS already requires, plus the change to `setup.py`. Is there any reason this PR can't be merged?

**Comment by MacLake** [comment]
Yes, and even if you still use Django 2.2, it doesn’t work with `django-cms>3.7.2`, which is a bit strange, as `djangocms-column` was installed with `djangocms-installer` afair.

Even if I want to get rid of `djangocms-column`, as I have written a grid plugin for Fomantic UI, we still have content, which would disappear when I delete `djangocms-column `.
