### ISSUE TITLE
remove/fix import `python_2_unicode_compatible`

### ISSUE THREAD

**Issue by tschale** [divio/djangocms-column#45]
It seems that a jump from django-cms 3.7.1 to 3.7.2 causes djangocms-column to break, as they removed `python_2_unicode_compatible` from `cms/utils/compat/dj.py` (https://github.com/divio/django-cms/commit/6c92fbecbff90036fd944345850b47f874050e3a#diff-e23ce56a2a8ee3898d5da04c957ccd6c)

Can someone confirm this?

**Comment by sidneywidmer** [comment]
Same for me 👍

**Comment by Bodyhealer** [comment]
confirmed.
`from six import python_2_unicode_compatible`

**Comment by TheSeg** [comment]
I also have this issue. If pull request #43 was accepted, then `six` would get imported into the project and should resolve the issue.

**Comment by vakorol** [comment]
I confirm this issue. It was originally reported in the `django-cms` project:
https://github.com/divio/django-cms/issues/6846

**Comment by vakorol** [comment]
Please increase the priority of this issue, as it is blocking from upgrading to Django CMS >= 3.7.4, which includes a security vulnerability (http://docs.django-cms.org/en/latest/upgrade/3.7.4.html).
