### ISSUE TITLE
TemplateSyntaxError

### ISSUE THREAD

**Issue by kainbacher** [divio/djangocms-column#5]
If i add the Plugin i get an this Error. Is there something wrong with my conf?

Exception Type:	TemplateSyntaxError
Exception Value:	
Invalid block tag: 'render_plugin', expected 'empty' oder 'endfor'
Exception Location:	/Users/Roland/PythonEnvs/django14-bluetechnix/lib/python2.7/site-packages/django/template/base.py in invalid_block_tag, line 320
Python Executable:	/Users/Roland/PythonEnvs/django14-bluetechnix/bin/python

**Comment by mkoistinen** [comment]
Cannot reproduce in supported CMSes.
